.load ./url
.selftest --init

insert into selftest (op, cmd, ans) values
    ('memo', 'url_user tests', ''),
    ('run', "select url_user('http://example.com')", ''),
    ('run', "select url_user('http://foobar@example.com')", 'foobar'),
    ('run', "select url_user('http://foobar:hunter2@example.com')", 'foobar'),
    ('memo', 'url_password tests', ''),
    ('run', "select url_password('http://example.com')", ''),
    ('run', "select url_password('http://foobar@example.com')", ''),
    ('run', "select url_password('http://foobar:hunter2@example.com')", 'hunter2'),
    ('memo', 'url_options tests', ''),
    ('run', "select url_options('http://example.com')", ''),
    ('memo', 'url_host tests', ''),
    ('run', "select url_host('http://example.com')", 'example.com'),
    ('memo', 'url_port tests', ''),
    ('run', "select url_port('http://example.com')", 80),
    ('run', "select url_port('http://example.com:8080')", 8080),
    ('run', "select url_port('https://example.com')", 443),
    ('memo', 'url_path tests', ''),
    ('run', "select url_path('http://example.com')", '/'),
    ('run', "select url_path('http://example.com/')", '/'),
    ('run', "select url_path('http://example.com/foo/bar')", '/foo/bar'),
    ('run', "select url_path('http://example.com/foo/bar?q=query')", '/foo/bar'),
    ('memo', 'url_query tests', ''),
    ('run', "select url_query('http://example.com')", ''),
    ('run', "select url_query('http://example.com/')", ''),
    ('run', "select url_query('http://example.com?q=query')", 'q=query'),
    ('run', "select url_query('http://example.com/?q=query')", 'q=query'),
    ('run', "select url_query('http://example.com/foo/bar?q=query')", 'q=query'),
    ('memo', 'url_fragment tests', ''),
    ('run', "select url_fragment('http://example.com')", ''),
    ('run', "select url_fragment('http://example.com/')", ''),
    ('run', "select url_fragment('http://example.com#placeholder')", 'placeholder'),
    ('run', "select url_fragment('http://example.com/#placeholder')", 'placeholder'),
    ('memo', 'url_scheme tests', ''),
    ('run', "select url_scheme('http://example.com')", 'http'),
    ('run', "select url_scheme('https://example.com')", 'https');

.selftest
